// <auto-generated />
namespace EntityFrameworkTest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedLicensePlate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedLicensePlate));
        
        string IMigrationMetadata.Id
        {
            get { return "201307120602307_Added LicensePlate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
